// <auto-generated />
using LibraryMinimalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryMinimalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryMinimalApi.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "Stephen King",
                            Description = "A horror novel about a haunted hotel.",
                            Genre = 0,
                            IsAvailable = true,
                            PublicationYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "J.R.R. Tolkien",
                            Description = "A fantasy novel about a hobbit's adventure.",
                            Genre = 2,
                            IsAvailable = false,
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Gillian Flynn",
                            Description = "A thriller about a woman's mysterious disappearance.",
                            Genre = 1,
                            IsAvailable = true,
                            PublicationYear = 2012,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Jane Austen",
                            Description = "A classic romance about love and social standing.",
                            Genre = 3,
                            IsAvailable = true,
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Dan Brown",
                            Description = "A mystery thriller about a secret society and ancient symbols.",
                            Genre = 4,
                            IsAvailable = false,
                            PublicationYear = 2003,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            BookID = 6,
                            Author = "George Orwell",
                            Description = "A dystopian novel about a totalitarian regime.",
                            Genre = 2,
                            IsAvailable = true,
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            BookID = 7,
                            Author = "Bram Stoker",
                            Description = "A horror novel about the legendary vampire Count Dracula.",
                            Genre = 0,
                            IsAvailable = false,
                            PublicationYear = 1897,
                            Title = "Dracula"
                        },
                        new
                        {
                            BookID = 8,
                            Author = "Stieg Larsson",
                            Description = "A mystery thriller about a journalist and a hacker solving a cold case.",
                            Genre = 4,
                            IsAvailable = true,
                            PublicationYear = 2005,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            BookID = 9,
                            Author = "Stephenie Meyer",
                            Description = "A romance fantasy novel about a girl falling in love with a vampire.",
                            Genre = 3,
                            IsAvailable = true,
                            PublicationYear = 2005,
                            Title = "Twilight"
                        },
                        new
                        {
                            BookID = 10,
                            Author = "Suzanne Collins",
                            Description = "A dystopian novel about a fight to the death in a televised arena.",
                            Genre = 2,
                            IsAvailable = false,
                            PublicationYear = 2008,
                            Title = "The Hunger Games"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
